### ISSUE TITLE
Conda-forge  package 

### ISSUE THREAD

**Issue by hmacdope** [whitead/molbloom#20]
It would be super cool to package this on `conda-forge`. 

I am happy to make the recipie, but to make it from the PyPi source will need to fix #18 first. Otherwise we can do straight from github repo (probably easier anyway).  Would you be open to this @whitead?

**Comment by whitead** [comment]
Sure! It does have wheels and I've approved your manifest changes. Let me know if you need anything else!

**Comment by hmacdope** [comment]
Recipie is WIP here: https://github.com/conda-forge/staged-recipes/pull/25943, building from git tarball.

**Comment by hmacdope** [comment]
Done now @whitead!
