### ISSUE TITLE
Streamline the download process

### ISSUE THREAD

**Issue by WardLT** [whitead/molbloom#3]
I'm looking to use a few different catalogs and figure that it'd be great to share them once I've made them. 

Do you have any thoughts already on how to include such a feature? I've got storage that we can use for them.

**Comment by whitead** [comment]
Try this

```py
from urllib.request import urlretrieve
from molbloom.bloom import BloomFilter
urlretrieve(
    'https://example.com/filter.bloom', 'filter.bloom'
)
bf = BloomFilter('filter.bloom')
# as statement
'CCCCON' in bf

# or as function
def my_buy(s, bf=bf):
    return s in bf
```

**Comment by whitead** [comment]
Please re-open if this did not answer your question!
